### PR TITLE
[6.x] Cannot read properties of null (reading 'classList') & TypeErro…

### PR DESCRIPTION
**Pull request by Devsome**
Hello and thanks for making Statamic 6. I've got two errors after updating to 6.2.2 from 6.1.x.
On the `cp/collections/pages/entries/page-1094_en` site I got these two javascript errors
```javascript
index-Bwt0BGYS.js:132568 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'classList')
    at watch$1.immediate (index-Bwt0BGYS.js:132568:14)
    at callWithErrorHandling (index-Bwt0BGYS.js:2270:19)
    at callWithAsyncErrorHandling (index-Bwt0BGYS.js:2277:17)
    at baseWatchOptions.call (index-Bwt0BGYS.js:8303:48)
    at job (index-Bwt0BGYS.js:1998:18)
    at watch$2 (index-Bwt0BGYS.js:2033:7)
    at doWatch (index-Bwt0BGYS.js:8331:23)
    at watch$1 (index-Bwt0BGYS.js:8264:10)
    at index-Bwt0BGYS.js:132566:9
```

```javascript
index-Bwt0BGYS.js:110832 Uncaught (in promise) TypeError: tab.sections.some is not a function
    at index-Bwt0BGYS.js:110832:29
    at wrappedFn (index-Bwt0BGYS.js:1101:19)
    at Array.filter (<anonymous>)
    at apply$1 (index-Bwt0BGYS.js:1109:27)
    at Proxy.filter (index-Bwt0BGYS.js:1001:12)
    at ComputedRefImpl.fn (index-Bwt0BGYS.js:110831:29)
    at refreshComputed (index-Bwt0BGYS.js:648:29)
    at get value (index-Bwt0BGYS.js:1833:5)
    at setup (index-Bwt0BGYS.js:110849:45)
    at callWithErrorHandling (index-Bwt0BGYS.js:2270:19)
```

I tried it once with cp:dev as well as in production mode and the cp data from the vendor. I am currently using Statamic version 6.2.2 PRO. 

Before:
image

After:
image

Since this is my first PR in a large project, please let me know if there is anything else I need to provide. Thank you for reading.

### CODE REVIEW

**Comment by jasonvarga** [comment]
If this error only started occurring between 6.1 and 6.2.2, I would expect it would be something in those releases that caused it. I don't think the code in this PR was modified in that period. But thanks for the PR anyway, we'll verify it during the review!

**Comment by Devsome** [comment]
Thanks for the quick answer. I just tried again to pinpoint the problem and tested versions 6.0.0, 6.1.0, 6.2.0, and 6.2.2.
After switching to the other versions, I performed the following steps.
1. Deleted the vendor folder in public.
2. php artisan vendor:publish --tag=statamic-cp
3. yarn cp:build
4. yarn build
5. php artisan optimize:clear

The error occurred in every version. I will investigate it further.

**Comment by Devsome** [comment]
Good news, I was able to reproduce my error. It was due to my collection page blueprint, which had a formatting error. I hadn't thought of that. I'll close the PR for now.
