### ISSUE TITLE
Updating to 3.0.28 causes duplicate field errors

### ISSUE THREAD

**Issue by reuank** [statamic/cms#2869]
## Bug Description
After updating to 3.0.28, all pages are broken. On every page, I get very strange error messages like `Duplicate field [how_tech_how_tech_cta_button_call_to_action_button] on blueprint [home]` (see screenshot below). However, there is no such field defined in my home blueprint.

I use prefixed fieldsets in many blueprints, which also sometimes contain prefixed fieldsets, e.g.:
```yaml
# part of blueprint home.yaml
how_we_work:
    display: 'How we work'
    fields:
      -
        import: content_block
        prefix: how_
```

```yaml
# part of fieldset content_block.yaml
  -
    import: cta_button
    prefix: cta_button_
```

```yaml
# part of fieldset cta_button.yaml
title: 'Call to Action Button'
fields:
  -
    handle: call_to_action_button
    field:
      type: section
```

This has never caused any issues before. After downgrading to 3.0.27, the errors disappeared. 

## Extra Detail
![grafik](https://user-images.githubusercontent.com/6730567/99667788-28d85480-2a6d-11eb-9cd8-c7bf897d5f41.png)

## Environment
Statamic 3.0.28 Pro
Laravel 7.23.2
PHP 7.4.8
statamic/seo-pro 2.0.14
statamic/ssg 0.2.0

**Comment by jeremydouglas** [comment]
Confirmed, I came here to log this bug.

**Comment by jackmcdade** [comment]
We're on it!
