### ISSUE TITLE
Revisions broken in v3.2.27

### ISSUE THREAD

**Issue by aaron-elvie** [statamic/cms#4944]
### Bug description

Since upgrading to v3.2.27 revisions no longer work. 

The slug appears to be a missing argument to the `show` method on the `EntryRevisionsController`

Exception:

Too few arguments to function Statamic\\Http\\Controllers\\CP\\Collections\\EntryRevisionsController::show(), 4 passed in site/vendor/laravel/framework/src/Illuminate/Routing/Controller.php on line 54 and exactly 5 expected

### How to reproduce

Upgrade from v3.2.26 to v3.2.27
Turn on revisions for a collection
Create a revision
View history and select revision
See continuous loading indicator and 500 HTTP response.

### Versions

Statamic 3.2.27 Pro
Laravel 8.76.2
PHP 7.3.32
statamic/eloquent-driver 0.1.2

### Installation

Existing Laravel app

**Comment by jasonvarga** [comment]
Thanks for the report, we'll get right on that.
