### ISSUE TITLE
"This URI has already been taken." when saving a new entry again if you use the "Continue Editing" after save option

### ISSUE THREAD

**Issue by bland-industries** [statamic/cms#10504]
### Bug description

When trying to save again, a new entry with a route and slug, you get an error of "This URI has already been taken." if you use the "Continue Editing" after save option. It seems that after you save, the browser is not redirected to the newly saved entry so it thinks the user is trying to save a second new entry.

### How to reproduce

1. Create a collection with a route: `this-is-a-test/{slug}`
2. Create an Entry
3. Set "After Saving" radio option to "Continue Editing"
4. Type in a title like "This is a test. Please ignore this." and hit tab to make sure slug field is set
5. Click "Save & Publish"
6. After entry is saved click "Save & Publish" again.
7. Error "This URI has already been taken." will appear by the slug field
8. url is still "/collections/tests/entries/create/default"

### Logs

```shell
N/A
```

### Environment

```yaml
Environment
Application Name: 
Laravel Version: 10.48.12
PHP Version: 8.1.27
Composer Version: 2.6.6
Environment: local
Debug Mode: ENABLED
URL: 
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: errorlog
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 15
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.7.2 PRO

Statamic Addons
alt-design/alt-redirect: 1.3.2
aryehraber/statamic-logbook: 3.3.0
doefom/statamic-export: 0.4.0
jacksleight/statamic-bard-texstyle: 3.2.2
kadegray/statamic-country-and-region-fieldtypes: 1.2.4
rias/statamic-color-swatches: 2.3.0
simonridley/tracking-code-manager: 1.0.2
statamic/collaboration: 1.0.0
statamic/eloquent-driver: 4.2.0
stillat/relationships: 2.2.0
webographen/statamic-admin-log: 1.1.0

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: file
Collection Trees: file
Collections: file
Entries: file
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Taxonomies: file
Terms: file
Tokens: file
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
I've just followed the reproduction steps you provided, however, the saving seems to be working as expected for me.

https://github.com/user-attachments/assets/f9811f64-bd01-44f0-9bdf-55e59c657acd

After creating an entry, it'll take you to another page, with a different URL. Is that happening for you? Does the URL change after creating an entry?

If it's not, it sounds like the entry gets created but then there's some sort of error happening which is preventing you from being redirected to the edit URL, which means that the second time you attempt to save it actually tries to create a new entry rather than edit the one you just created.

**Comment by bland-industries** [comment]
> I've just followed the reproduction steps you provided, however, the saving seems to be working as expected for me.
> 
>  CleanShot.2024-07-25.at.17.32.48.mp4 
> 
> After creating an entry, it'll take you to another page, with a different URL. Is that happening for you? Does the URL change after creating an entry?
> 
> If it's not, it sounds like the entry gets created but then there's some sort of error happening which is preventing you from being redirected to the edit URL, which means that the second time you attempt to save it actually tries to create a new entry rather than edit the one you just created.
> 
> Are there any errors in the log file (`storage/logs`)? Do you have any custom event listeners?

Ok. I will double check my instance and see, appreciate the time checking

**Comment by duncanmcclean** [comment]
> The same issue appears for me after the update to v5. My collection has a route like `{{ mount }}/{{ slug }}-{{ date_start format="j-n-Y" }}`. With v4 it was possible to use the same `slug` for multiple entries as long as it was unique together with `date_start`. Now updating existing entries and creating new entries is not possible.

Are there any errors in your log file (`storage/logs`)? Do you have any custom event listeners?

**Comment by bland-industries** [comment]
It seems that it is a JS error after the save process happens `TypeError: this.nextTick is not a function. (In 'this.nextTick(()=>this.trackDirtyState=!0)', 'this.nextTick' is undefined`

This was part of the `resources/js/components/entries/PublishForm.js` file that was copied from the cms into our project. It looks like from reading this commit https://github.com/statamic/cms/commit/b1fd3f1160250c5f8938e699e783250a6e8e9485 it was a bug that we copied and never updated after the fix.

Thanks for your time

**Comment by duncanmcclean** [comment]
Out of interest, why have you copied the `PublishForm.vue` component into your project? We don't recommend doing it.
